log:
  level: warn
  file: "/var/log/mosdns.log"

api:
  http: "127.0.0.1:9091" # api 监听地址

include:
  - "/etc/mosdns/dat_exec.yaml"
  - "/etc/mosdns/dns.yaml"

plugins:
  - tag: reject_null_domain
    type: sequence
    args:
      - exec: query_summary reject_null_domain
      - exec: reject 3

  - tag: reject_qtype65
    type: sequence
    args:
      - exec: query_summary reject_qtype65
      - exec: reject 3
  
  - tag: reject_block
    type: sequence
    args:
      - exec: query_summary reject_block
      - exec: reject 5

  # - tag: reject_ad
  #   type: sequence
  #   args:
  #     - exec: query_summary reject_adlist
  #     - exec: reject 3

  ################ 序列 #################
  - tag: dns_nocn
    type: fallback
    args:
      primary: forward_remote
      secondary: forward_local
      threshold: 5000
      always_standby: false
  
  # dns-cn 序列
  - tag: dns_cn
    type: sequence
    args:
      - exec: $forward_local

  - tag: dns_nocn_seq
    type: sequence
    args:
      - exec: query_summary dns_nocn
      - exec: $dns_nocn

  - tag: dns_cn_seq
    type: sequence
    args:
      - exec: query_summary dns_cn
      - exec: $dns_cn

  - tag: fallback_seq # 其他特殊情况统一交给clash处理
    type: sequence
    args:
      - exec: query_summary fallback
      - exec: $forward_openclash

  - tag: other_seq # 预处理序列的特殊情况统一使用 dns_cn 处理
    type: sequence
    args:
      - exec: query_summary other
      - exec: $dns_cn

  # query cn 域名
  - tag: query_cn
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: $dns_cn_seq
      - matches: qname $ddnslist
        exec: return
      - matches: qname $whitelist
        exec: return
      - matches: "!resp_ip $geoip_cn" # 响应非 cn ip
        exec: drop_resp # 丢弃

  # query nocn 域名
  - tag: query_nocn
    type: sequence
    args:
      - exec: $no_ecs
      - exec: $dns_nocn_seq
      - matches: "resp_ip $geoip_cn" # 响应存在 cn ip
        exec: drop_resp # 丢弃

  - tag: query_gfw
    type: sequence
    args:
      - exec: $no_ecs
      - exec: $forward_openclash

  # query fallback
  - tag: query_fallback
    type: sequence
    args:
      - exec: $no_ecs
      - exec: $fallback_seq

  # # query lan
  # - tag: query_lan
  #   type: sequence
  #   args:
  #     - exec: $cache_lan
  #     - matches: has_resp # 命中了 lan cache
  #       exec: return
  #     # - exec: $no_ecs
  #     - exec: $local_seq

  - tag: pre_handle
    type: sequence
    args:
      - exec: $ttl_modify # 修改 ttl（单位：秒）
      - exec: accept # 接受响应,终止流程

  - tag: main_handle
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: ttl 5-5
      - matches: "!qname $ddnslist"
        exec: $ttl_modify
      - exec: accept # 接受响应,终止流程

  # pre_sequence 结果处理 
  - tag: has_resp_pre
    type: sequence
    args:
      - matches: has_resp # 如果 pre 序列已有响应
        exec: goto pre_handle

  # main_sequence 结果处理
  - tag: has_resp_main
    type: sequence
    args:
      - matches: has_resp
        exec: goto main_handle

  # pre_sequence
  - tag: pre_sequence
    type: sequence
    args:
      - matches: qtype 65 # TYPE 65 类型|DNS服务器状态，拒绝该类型可避免某些IOS 应用无法上网。
        exec: $reject_qtype65
      - matches: "qname keyword::" # 无效域名
        exec: $reject_null_domain
      - matches:  # PTR 黑名单
        - "qtype 12"
        - "qname $local_ptr"
        exec: reject 3

      - exec: $hosts  # hosts
      - exec: jump has_resp_main
      - exec: $redirect # redirect
      - exec: jump has_resp_main
      - matches: qname $blocklist
        exec: $reject_block
      - matches: qtype 255 # TYPE 255 类型|DNS服务器拓展支持
        exec: $other_seq
      - exec: jump has_resp_pre
      # - matches: ptr_ip $geoip_private # private ip
      #   exec: $query_lan
      

  # main_sequence
  - tag: main_sequence
    type: sequence
    args:
      # - matches: qname $geosite_ads-all # ad 域名（去广告由AdGuardHome完成）
      #   exec: $reject_ad
      # - exec: $cache_wan # 缓存功能由AdGuardHome完成
      # - exec: jump has_resp_main

      - matches: qname $ddnslist  # ddns
        exec: $query_cn
      - exec: jump has_resp_main
      - matches: qname $geosite_cn # cn 域名
        exec: $query_cn
      - exec: jump has_resp_main
      # 检查是否符合GFW域名规则
      - matches: qname $geosite_gfw
        exec: $query_gfw
      - exec: jump has_resp_main
      - matches: qname $geosite_location-!cn # 非 cn 域名
        exec: $query_nocn
      - exec: jump has_resp_main
      # 漏网之鱼
      - exec: $query_fallback
      - exec: jump has_resp_main

  - tag: sequence
    type: sequence
    args:
      - exec: $pre_sequence # 预处理
      - exec: $main_sequence # 主执行序列

  # 在 5353 端口启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: sequence
      listen: :5335
  - type: tcp_server
    args:
      entry: sequence
      listen: :5335
